# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dad630335876d4ceab163d737856c74ec2c91acf0539c1623ecbaaedef602de6d5687d7ea61d0c12c42eadbc6abebb87484c3f0fa5bb74834f23954251fe510f

test:
  secret_key_base: a2607941077aaf5411d08595c91a931c84751ac9bc3afc69f0724e6ad93dff96eda58ac170b84a6634458cd3d7fda5da92021cf3ead16b31deb501b6e5f1ba92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
